version: '3.7'

x-network:
  &network
  networks:
    - your_network

services:
  traefik:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    <<: *network

  client:
    build:
      context: ./client
    labels:
      - traefik.http.routers.client-cheatuniverse.rule=Host(`domain.com`)
